const slides = [
    {
      url: '/image/2026106.jpg',
      title:'Death Note',
      cont:'An intelligent high school student goes on a secret crusade to eliminate criminals from the world after discovering a notebook capable of killing anyone whose name is written into it.',
      time:'24m',
      date:'Oct 3,2006',
      detail:"Death Note is a Japanese manga series written by Tsugumi Ohba and illustrated by Takeshi Obata. The story follows Light Yagami, a teen genius who discovers a mysterious notebook: the 'Death Note', which belonged to the shinigami Ryuk, and grants the user the supernatural ability to kill anyone whose name is written in its pages. The series centers around Light's subsequent attempts to use the Death Note to carry out a worldwide massacre of individuals whom he deems immoral and to create a crime-free society, using the alias of a god-like vigilante named 'Kira', and the subsequent efforts of an elite Japanese police task force, led by enigmatic detective L, to apprehend him. Death Note ran in Shueisha's manga magazine Weekly Shōnen Jump from December 2003 to May 2006. Its 108 chapters were collected in 12 tankōbon volumes.",
      japanese:"デスノート, Desu Nōto",
      aired:"October 4, 2006 to June 27, 2007",
      premiered:"Summer 2006",
      status:"Finished",
      imdb:"9.0 / 10",
      genre:"Horror, Drama, Mystery, Thriller, Suspense, Crime",
      producer:"Toshio Nakatani, Manabu Tamura, Masao Maruyama",
      studio:"Madhouse"
    },
    {
      url: '/image/108250.jpg',
      title:'Attack On Titan',
      cont:'Attack on Titan is a Japanese dark fantasy and post-apocalyptic anime TV series adapted from the manga of the same name by Hajime Isayama. It is set in a world where humanity lives inside cities surrounded by enormous walls due to the Titans, gigantic humanoid beings who devour humans seemingly without reason.',
      time:'20m',
      date:'Jan 13,2018',
      detail:"Attack on Titan is a Japanese dark fantasy anime television series, adapted from the manga of the same name by Hajime Isayama, that premiered on April 7, 2013. It has aired on NHK General TV in Japan,[e] and Aniplus Asia in various Asia-Pacific countries.In the United States and Canada, the series has streamed on Crunchyroll, Funimation, Netflix, Amazon Prime Video, and Hulu, in addition to airing on Adult Swim's Toonami programming block in the U.S.",
      japanese:"進撃の巨人, Shingeki no Kyojin",
      aired:"Jan 13, 2018 to present",
      premiered:"Winter 2018",
      status:"Currently Airing",
      imdb:"9.0 / 10",
      genre:"Action, Dark-fantasy, Post-apocalyptic",
      producer:"Tetsuya Kinoshita, Kensuke Tateishi, Toshihiro Maeda",
      studio:"Wit Studio (1–59), MAPPA (60–)"
    },
    {
      url: '/image/1000030.jpg',
      title:'Demon Slayer',
      cont:'Demon Slayer is a Japanese manga series written and illustrated by Koyoharu Gotouge. It follows teenage Tanjiro Kamado, who strives to become a demon slayer after his family was slaughtered and his younger sister, Nezuko, turned into a demon.',
      time:'20m',
      date:'Apr 6,2019',
      detail:"Demon Slayer , 'Blade of Demon Destruction' is a Japanese manga series written and illustrated by Koyoharu Gotouge. It follows teenage Tanjiro Kamado, who strives to become a demon slayer after his family was slaughtered and his younger sister, Nezuko, turned into a demon. It was serialized in Shueishas shōnen manga magazine Weekly Shōnen Jump from February 2016 to May 2020, with its chapters collected in twenty-three tankōbon volumes. It has been published in English by Viz Media and simultaneously published by Shueisha on their Manga Plus platform.",
      japanese:"鬼滅の刃, Kimetsu no Yaiba",
      aired:"April 6, 2019 to present",
      premiered:"Summer 2019",
      status:"Currently Airing",
      imdb:"9.0 / 10",
      genre:"Adventure, Dark fantasy, Martial arts",
      producer:"Akifumi, Fujio Masanori Miyake, Yūma Takahashi, Hikaru Kondo (1–26), Takashi Takano (34–44)",
      studio:"Ufotable"
    },
    {
      url: '/image/713076.png',
      title:'My Hero Academia',
      cont:'After he saves a bully from a Villain, a normal student is granted a superpower that allows him to attend a high school training academy for Heroes.',
      time:'24m',
      date:' Oct 12,2019',
      detail:"My Hero Academia is a Japanese superhero manga series written and illustrated by Kōhei Horikoshi. It has been serialized in Shueisha's Weekly Shōnen Jump since July 2014, with its chapters additionally collected into 35 tankōbon volumes as of July 2022. Set in a world where superpowers (called 'Quirks') have become commonplace, the story follows Izuku Midoriya, a boy who was born without a Quirk but still dreams of becoming a superhero himself. He is scouted by All Might, Japan's greatest hero, who bestows his Quirk to Midoriya after recognizing his potential, and helps to enroll him in a prestigious high school for superheroes in training.",
      japanese:"僕のヒーローアカデミア, Boku no Hīrō Akademia",
      aired:"October 12, 2019 to present",
      premiered:"Autumn 2019",
      status:"Currently Airing",
      imdb:"8.4 / 10",
      genre:"Adventure, Science, fantasy, Superhero",
      producer:"Kazumasa Sanjōba, Hiroshi Kamei, Naoki Amano",
      studio:"Bones"
    },
    {
      url: '/image/wp1809904-one-punch-man-wallpapers.jpg',
      title:'One Punch Man',
      cont:'One-Punch Man is a Japanese superhero manga series created by One. It tells the story of Saitama, a superhero who, because he can defeat any opponent with a single punch, grows bored from a lack of challenge.',
      time:'24m',
      date:'Oct 4,2015',
      detail:"One-Punch Man is a Japanese superhero manga series created by One. It tells the story of Saitama, a superhero who, because he can defeat any opponent with a single punch, grows bored from a lack of challenge. One wrote the original webcomic manga version in early 2009. A digital manga remake began publication on Shueisha's Tonari no Young Jump website in June 2012. Written by One and illustrated by Yusuke Murata, its chapters are periodically compiled and published into individual tankōbon volumes. As of June 2022, 26 volumes have been released. In North America, Viz Media has licensed the remake manga for English language release and has serialized it in its Weekly Shonen Jump digital magazine.",
      japanese:"ワンパンマン, Wanpanman",
      aired:"October 5, 2015 to present",
      premiered:"Autumn 2015",
      status:"Currently Airing",
      imdb:"8.4 / 10",
      genre:"Action, Comedy, Superhero",
      producer:"Chinatsu Matsui, Nobuyuki Hosoya, Keita Kodama (season 1), Ayuri Taguchi (season 1),     Sōta Satō (season 2)"
    },
    {
      url: '/image/1116284.jpg',
      title:'Jujutsu Kaisen',
      cont:"A boy swallows a cursed talisman - the finger of a demon - and becomes cursed himself. He enters a shaman's school to be able to locate the demon's other body parts and thus exorcise himself.",
      time:'22m',
      date:'Oct 3,2020',
      detail:"Jujutsu Kaisen is a Japanese manga series written and illustrated by Gege Akutami. It has been serialized in Shueisha's shōnen manga magazine Weekly Shōnen Jump since March 2018, with its chapters collected and published in 20 tankōbon volumes as of August 2022. The story follows high school student Yuji Itadori as he joins a secret organization of Jujutsu Sorcerers in order to kill a powerful Curse named Ryomen Sukuna, of whom Yuji becomes the host. Jujutsu Kaisen is a sequel to Akutami's Tokyo Metropolitan Curse Technical School, serialized in Shueisha's Jump GIGA from April to July 2017, later collected in a tankōbon volume, retroactively titled as Jujutsu Kaisen 0, in December 2018.",
      japanese:"呪術廻戦, Jujutsu Kaisen",
      aired:"October 3, 2020 to present",
      premiered:"Autumn 2020",
      status:"Currently Airing",
      imdb:"8.6 / 10",
      genre:"Adventure, Dark, fantasy, Supernatural",
      producer:"Hiroaki Matsutani, Makoto Kimura, Toshihiro Maeda, Yoshiaki Takagaki, Yuriha Murai",
      studio:"MAPPA"
    },
    {
      url: '/image/1231318.png',
      title:'Spy x Family',
      cont:"An elegant and hilarious action-comedy series, SPY x FAMILY tells the story of a suave superspy who must cobble together a fake family in order to get close to a target, not realising the fake wife and daughter he's enlisted are an assassin and a telepath",
      time:'23m',
      date:'Apr 3,2022',
      detail:"Spy × Family (stylized as SPY×FAMILY; pronounced 'Spy Family') is a Japanese manga series written and illustrated by Tatsuya Endo. The story follows a spy who has to 'build a family' to execute a mission, not realizing that the girl he adopts as his daughter is a telepath, and the woman he agrees to be in a marriage with is a skilled assassin. The series has been serialized biweekly on Shueisha's Shōnen Jump+ application and website since March 2019, with the chapters collected in nine tankōbon volumes as of April 2022. It was licensed in North America by Viz Media.",
      japanese:"家族の肖像, SPY×FAMILY",
      aired:"April 9, 2022 to present",
      premiered:"Summer 2022",
      status:"Currently Airing",
      imdb:"8.6 / 10",
      genre:"Action, Comedy, Spye",
      producer:"Kazuhiro Furuhashi, Kazuhiro Furuhashi, Makoto Miyazaki, Shūhei Mutsuki",
      studio:"Wit Studio, CloverWorks "
    },
    {
      url: '/image/mob.jpg',
      title:'Mob Psycho 100',
      cont:"Mob, a school boy with psychic powers, attempts to juggle school life and his job as an exorcist. However, Mob's emotions become more and more unstable as opposing groups of spirits, psychics and con-artists try to trick him.",
      time:'22m',
      date:'July 12,2016',
      detail:"Mob Psycho 100 is a Japanese manga series written and illustrated by One. It was serialized on Shogakukan's Ura Sunday website from April 2012 to December 2017. It has been also available online on Shogakukan's mobile app MangaONE since December 2014. Shogakukan compiled its chapters into sixteen tankōbon volumes.",
      japanese:"モブサイコ100, Mobu Saiko Hyaku",
      aired:"July 12,2016 to present",
      premiered:"Summer 2026",
      status:"Currently Airing",
      imdb:"8.6 / 10",
      genre:"Action, Comedy, Supernatural",
      producer:"Akio Matsuda, Hirotsugu Ogisu, Yūki Nagano",
      studio:"Bones"
    },
    {
      url: '/image/840936.jpg',
      title:'Death Parade',
      cont:"After death, humans go to either heaven or hell. But for some, at the instant of their death, they arrive at the Quindecim, a bar attended by the mysterious white-haired Decim",
      time:'24m',
      date:' Jan 9,2015',
      detail:"Death Parade is a Japanese anime television series created, written, and directed by Yuzuru Tachikawa and produced by Madhouse. The series spawned from a short film, Death Billiards, which was originally produced by Madhouse for the Young Animator Training Project's Anime Mirai 2013 and released in March 2013. The television series aired in Japan between January and March 2015. It is licensed in North America by Funimation and in the United Kingdom by Anime Limited, the latter of which was eventually cancelled. The series was obtained by Madman Entertainment for digital distribution in Australia and New Zealand.",
      japanese:"デス・パレード, Desu Parēdo",
      aired:"January 9, 2015 to present",
      premiered:"Winter 2015",
      status:"Currently Airing",
      imdb:"7.9 / 10",
      genre:"Psychological, Thriller",
      producer:"Toshio Nakatani, Kojiro Naotsuka, Hiroyuki Inage, Shunsuke Nara, Ayuri Taguchi",
      studio:"Madhouse"
    },
    {
      url: '/image/598628.jpg',
      title:'Assassination Classroom',
      cont:"Forget about homework and pop quizzes. The students of Class 3E have a far more important assignment: kill their teacher before the end of the year.",
      time:'21m',
      date:'Jan 9,2015',
      detail:"Assassination Classroom is a Japanese science fiction comedy manga series written and illustrated by Yusei Matsui. The series follows the daily life of an extremely powerful octopus-like being working as a junior high homeroom teacher, and his students dedicated to the task of assassinating him to prevent Earth from being destroyed. The students are considered 'misfits' in their school and are taught in a separate building; the class he teaches is called 3-E. It was serialized in Shueisha's Weekly Shōnen Jump magazine from July 2012 to March 2016, with its chapters collected in twenty-one tankōbon volumes",
      japanese:"暗殺教室, Ansatsu Kyōshitsu",
      aired:"January 9, 2015 to June 15, 2015",
      premiered:"Winter 2015",
      status:"Finished",
      imdb:"8 / 10",
      genre:"Action, Science fiction, Comedy",
      producer:"Noriko Ozaki",
      studio:"Lerche"
    },
    
  ];
  export default slides;